# Generated by Django 4.1.1 on 2022-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
