# Generated by Django 4.1.1 on 2022-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, default=None, verbose_name='Сообщение'),
        ),
    ]
