# Generated by Django 4.1.1 on 2022-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactform_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=None, verbose_name='Дата создания'),
        ),
    ]
