# Generated by Django 4.1.1 on 2022-09-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contactform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tariff',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='main.tariff', verbose_name='Рассчитанный тариф'),
        ),
        migrations.AddField(
            model_name='order',
            name='usdt_amount',
            field=models.FloatField(default=0, verbose_name='Сумма в USDT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='main.contactform', verbose_name='Контактное лицо'),
        ),
    ]
