# Generated by Django 4.1.1 on 2022-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_tariff_order_usdt_amount_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tariff',
        ),
        migrations.AddField(
            model_name='order',
            name='convertation',
            field=models.FloatField(default=0, verbose_name='Конвертация'),
        ),
        migrations.AddField(
            model_name='order',
            name='documentation',
            field=models.FloatField(default=0, verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=150, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='operation',
            field=models.FloatField(default=0, verbose_name='Исполнение'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
